# Global settings
global:
  namespace: kafka-k8s

# Kafka configuration
kafka:
  enabled: true
  image: confluentinc/cp-kafka
  tag: 7.5.0
  replicas: 3
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092
  config:
    processRoles: "broker,controller"
    controllerQuorumVoters: "0@kafka-0.kafka.kafka-k8s.svc.cluster.local:29093,1@kafka-1.kafka.kafka-k8s.svc.cluster.local:29093,2@kafka-2.kafka.kafka-k8s.svc.cluster.local:29093"
    listeners: "PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:29093"
    listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
    controllerListenerNames: "CONTROLLER"
    interBrokerListenerName: "PLAINTEXT"
    offsetsTopicReplicationFactor: "3"
    groupInitialRebalanceDelayMs: "0"
    transactionStateLogMinIsr: "2"
    transactionStateLogReplicationFactor: "3"
    autoCreateTopicsEnable: "true"
    clusterId: "MkU3OEVBNTcwNTJENDM2Qk"
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  persistence:
    enabled: false
    size: 20Gi

# Schema Registry configuration
schemaRegistry:
  enabled: false

# Kafka UI configuration
kafkaUI:
  enabled: true
  image: provectuslabs/kafka-ui
  tag: latest
  replicas: 1
  config:
    kafka:
      clusters:
      - name: local
        bootstrapServers: "kafka-0.kafka.kafka-k8s.svc.cluster.local:29092,kafka-1.kafka.kafka-k8s.svc.cluster.local:29092,kafka-2.kafka.kafka-k8s.svc.cluster.local:29092"
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# Flink configuration
flink:
  enabled: true
  image: flink
  tag: 1.18.1-scala_2.12
  jobmanager:
    replicas: 1
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
  taskmanager:
    replicas: 2
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m" 