{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: {{ .Values.global.namespace }}
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - name: external
    port: 9092
    targetPort: 9092
    nodePort: 30092
{{- end }} 